---
name: AutoPluginUpdater
description: 'This system can update plugins automatically'
author: Rajador
discord: rajadortv
api: 2.0.0
depend:
  - SmartCommand
version: 1.2.0
main: rajadordev\autoupdater\Loader
permissions:
  apu.command.main:
    description: 'Allows player to use /apu command'
    default: true
  apu.command.setgittoken:
    description: 'allows player to set GitToken'
    default: op
  apu.command.version:
    description: 'Allows player to see the latest version of AutoPluginUpdater'
    default: true
...